services:
  database:
    container_name: schedule-database
    image: mysql:9
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=schedule
    ports:
      - 3306:3306
    volumes:
      - local:/var/lib/mysql
    networks:
      - api-database
  api:
    container_name: schedule-api
    build: /backend
    ports:
      - 8090:8090
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/schedule
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    depends_on:
      - database
    networks:
      - api-database
      - api-frontend
  frontend:
    container_name: schedule-frontend
    build:
      context: ./frontend
    ports:
      - 4200:80
    depends_on:
      - api
    networks:
      - api-frontend
networks:
  api-database:
    driver: bridge
  api-frontend:
    driver: bridge
volumes:
  local:
